---

- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - xquartz
        - android-studio
        - angry-ip-scanner
        - atom
        - adobe-air
        - blender
        - dockertoolbox
        - caffeine
        - chefdk
        - chromium
        - cyberduck
        - dia
        - dterm
        - fluid
        - google-chrome
        - hipchat
        - iterm2
        - shiftit
        - sourcetree
        - spotify
        - sqlitebrowser
        - steam
        - sublime-text
        - skype
        - unrarx
        - vlc
    - name: install cmata brew applications
      homebrew: name={{item}} state=latest
      with_items:
        - autoconf
        - automake
        - brew-cask
        - cmake
        - coreutils
        - ddrescue
        - gdbm
        - git
        - git-extras
        - git-flow
        - gnu-getopt
        - gnu-indent
        - gnu-sed
        - gnu-tar
        - gnupg
        - gnutls
        - gobject-introspection
        - graphviz
        - jmeter
        - libevent
        - libffi
        - libgpg-error
        - libksba
        - libnet
        - libpng
        - libtasn1
        - libtiff
        - libtool
        - libyaml
        - lua
        - lzip
        - memcached
        - mercurial
        - mutt
        - nginx-full
        - node
        - openssl
        - pbzip2
        - pcre
        - pkg-config
        - rarian
        - readline
        - redis
        - shmux
        - sox
        - sqlite
        - squid
        - tmux
        - tree
        - wget
        - xz
        - zsh

  roles:
    - profile-gopro

  vars:
    - computername: mbr-30479
    - git_user_name: Kevin
    - git_user_email: charles.mata@gmail.com
    - sublime_packages:
        - dest: "Alignment"
          repo: "https://github.com/wbond/sublime_alignment.git"
          version: "master"
        - dest: "BeautifyRuby"
          repo: "https://github.com/CraigWilliams/BeautifyRuby.git"
          version: "master"
        - dest: "Emmet"
          repo: "https://github.com/sergeche/emmet-sublime.git"
          version: "master"
        - dest: "Git"
          repo: "https://github.com/kemayo/sublime-text-git.git"
          version: "master"
        - dest: "Tomorrow Color Schemes"
          repo: "https://github.com/theymaybecoders/sublime-tomorrow-theme.git"
          version: "master"
        - dest: "ReactJS"
          repo: "https://github.com/reactjs/sublime-react.git"
          version: "master"
        - dest: "HTMLPrettify"
          repo: "https://github.com/victorporof/Sublime-HTMLPrettify.git"
          version: "master"
        - dest: "SideBarEnhancements"
          repo: "https://github.com/titoBouzout/SideBarEnhancements"
          version: "st3"
        - dest: "GitGutter"
          repo: "https://github.com/jisaacks/GitGutter.git"
          version: "master"
        - dest: "BracketHighlighter"
          repo: "https://github.com/facelessuser/BracketHighlighter.git"
          version: "master"
        - dest: "Theme - Soda"
          repo: "https://github.com/buymeasoda/soda-theme.git"
          version: "master"
        - dest: "Base16"
          repo: "https://github.com/chriskempson/base16-textmate.git"
          version: "master"
        - dest: "ApplySyntax"
          repo: "https://github.com/facelessuser/ApplySyntax.git"
          version: "master"
        - dest: "SublimeAllAutocomplete"
          repo: "https://github.com/alienhard/SublimeAllAutocomplete"
          version: "master"
        - dest: "Ansible"
          repo: "https://github.com/clifford-github/sublime-ansible.git"
          version: "master"
    - sublime_text_color_scheme: "Packages/Tomorrow Color Schemes/Tomorrow.tmTheme"
    - sublime_text_theme: "Soda Light.sublime-theme"
    - osx_defaults:
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: false
      - domain: 'com.apple.dock'
        key: 'minimize-to-application'
        type: integer
        value: 1
      - domain: 'com.apple.dock'
        key: 'show-process-indicators'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'expose-animation-duration'
        type: integer
        value: 0
      - domain: 'com.apple.dock'
        key: 'showhidden'
        type: boolean
        value: true
      - domain: 'com.apple.screencapture'
        key: 'location'
        type: string
        value: ~/Desktop/screenshots
      - domain: 'com.apple.menuextra.clock'
        key: 'DateFormat'
        type: string
        value: EEE MMM d  HH:mm
      - domain: 'com.apple.menuextra.battery'
        key: 'ShowPercent'
        type: string
        value: 'YES'
      - domain: 'com.apple.finder'
        key: 'FXPreferredViewStyle'
        type: string
        value: "clmv"
      - domain: 'com.apple.finder'
        key: 'FXDefaultSearchScope'
        type: string
        value: "SCcf"
      - domain: 'com.apple.finder'
        key: 'OpenWindowForNewRemovableDisk'
        type: boolean
        value: true
      - domain: 'com.apple.finder'
        key: '_FXShowPosixPathInTitle'
        type: boolean
        value: true
      - domain: 'com.apple.finder'
        key: 'AppleShowAllFiles'
        type: boolean
        value: true
      - domain: 'com.apple.DiskUtility'
        key: 'DUDebugMenuEnabled'
        type: boolean
        value: true
      - domain: 'com.apple.DiskUtility'
        key: 'advanced-image-options'
        type: boolean
        value: true
      - domain: 'com.apple.frameworks.diskimages'
        key: 'auto-open-ro-root'
        type: boolean
        value: true
      - domain: 'com.apple.frameworks.diskimages'
        key: 'auto-open-rw-root'
        type: boolean
        value: true
      - domain: 'com.google.Chrome'
        key: 'ExtensionInstallSources'
        type: array
        value:
          - "https://*.github.com/*"
          - "http://userscripts.org/*"
      - domain: 'com.google.Chrome.canary'
        key: 'ExtensionInstallSources'
        type: array
        value:
          - "https://*.github.com/*"
          - "http://userscripts.org/*"
